### ISSUE TITLE
嵌套申请问题，导致子申请无法正常回调

### ISSUE THREAD

**Issue by huanglinqing123** [mylhyl/AndroidAcp#15]
您好：
问题描述案例：
申请A权限，当A权限同意之后，之后在业务代码中不能再申请其他权限，申请后 将无法收到任何回调，代码示例如下：
 Acp.getInstance(BaseApplication.getContext()).request(AcpOptions.Builder()
                    .setPermissions(permission.ACCESS_COARSE_LOCATION,)
                    .build(),
                    object : AcpListener {
                        override fun onGranted() {
                             //权限同意
                            //部分业务逻辑
                             Acp.getInstance(){
                                //这里的权限无法收到回调
                             }
                        }

                        override fun onDenied(permissions: List<String>) {
                             //权限拒绝
                        }
                    })
此类问题，可以通过权限一起申请的方式完成，但是现在对权限管理越来越严格，在代码层面也希望封装成单独申请的模式，如Android 11中前台定位权限 要和后台定位权限分开申请，要先申请前台定位权限，才能申请后台定位权限 。，所以有了上述代码

问题原因：
查看了源码，问题原因在于，当第一次发起申请的时候，权限同意之后，调用了AcpManager的onDestroy方法，将mCallback置位null了，所以嵌套申请的时候 无法正常回调

**Comment by mylhyl** [comment]
什么业务场景需要嵌套申请？

**Comment by huanglinqing123** [comment]
Android11中 前后台定位权限，必须先申请前台定位权限同意后再申请后台定位权限，在一起申请会崩溃或者直接返回拒绝



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月5日(周五) 晚上7:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mylhyl/AndroidAcp] 嵌套申请问题，导致子申请无法正常回调 (Issue #15)




 
什么业务场景需要嵌套申请？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mylhyl** [comment]
OK
